### ISSUE TITLE
BuildGT header font shows up as serif

### ISSUE THREAD

**Issue by evan10s** [HackGT/live-site-old#36]
There's 2 warnings in the console about it:
```
Failed to decode downloaded font: https://live.build.hack.gt/assets/fonts/ProximaNovaRegular.otf
```
```
OTS parsing error: prep: table overruns end of file
```

**Comment by kexin-zhang** [comment]
I updated your `.gitattributes` - https://github.com/HackGT/live-site/blob/build-gt-live-site/.gitattributes
That should fix the problem. The font files are binaries and the line endings replacement was messing them up. It's fixed on https://live.build.hack.gt/ now as well.
