### ISSUE TITLE
Teeny 2020 Wrong Font on Safari

### ISSUE THREAD

**Issue by cchu70** [HackGT/live-site-old#80]
<img width="1197" alt="Screen Shot 2020-09-15 at 6 21 46 PM" src="https://user-images.githubusercontent.com/34669546/93271155-97a0e500-f780-11ea-87bc-a6618f8182db.png">

**Comment by Stephanie-A** [comment]
@evan10s any idea why this would be happening? It works fine locally and I tried clearing caching

**Comment by Stephanie-A** [comment]
Fixed in last push
