### ISSUE TITLE
Teeny 2020 missing Locations on the schedule

### ISSUE THREAD

**Issue by cchu70** [HackGT/live-site-old#81]
There are multiple "locations" (ie channels) for some of the tracks. For example, the location of Data science workshop 1 is "data science 1" and "data science 2." However, only the first one shows up.

Solutions:

- Make the locations generic (use "data science (1,2)"
- don't use locations 

<img width="324" alt="Screen Shot 2020-09-15 at 6 26 27 PM" src="https://user-images.githubusercontent.com/34669546/93271410-2a418400-f781-11ea-9a11-e9fcaf36457b.png">

**Comment by Stephanie-A** [comment]
@cchu70 maybe instead of location like that we just say Microsoft Teams?

**Comment by Stephanie-A** [comment]
@cchu70 fixed by changing to generic locations in cms
